### ISSUE TITLE
Resolving a promise should return the model and not the service output

### ISSUE THREAD

**Issue by faxioman** [tnguyen14/ampersand-sync-with-promise#10]
The resolve of a promise currently returns the service result parsed as json:
In line 146 of core.js module
```
resolve(body);
```
It would be better to resolve the ampersand model: the raw json returned by a rest service should be never used directly when working with ampersand. So, it could be:
```
resolve(model);
```

**Comment by tnguyen14** [comment]
Hi, this package is only meant as a light wrapper around https://github.com/AmpersandJS/ampersand-sync, so I try to stay as close to their API as possible. In that, they only return the `body` (see https://github.com/AmpersandJS/ampersand-sync/blob/master/core.js#L141)

FWIW, I think returning a model is assuming a bit too much in ampersand.

**Comment by faxioman** [comment]
Ok, it's worth noting that, without returning the model in promise, the method collection.fetchById is almost unusable in a promise context.
I think that is right to pass the body in the options.success method ... but not in the promise ;)

**Comment by tnguyen14** [comment]
Hi,

Could you explain in further details why you think this would make sense?
