### ISSUE TITLE
add support for .done and .catch methods

### ISSUE THREAD

**Issue by hngu** [tnguyen14/ampersand-sync-with-promise#3]
It would be nice to have these methods even though they are not part of the Promise/A+ spec. A lot of promise libraries have these methods including the one used in this package.

**Comment by tnguyen14** [comment]
Oh! you're right. Those methods are supported by then/promise. So I am not sure why those are not working for you then. It should just work...

**Comment by hngu** [comment]
Do you want a code snippet from me? Basically then .done callback does not get called at all.

**Comment by tnguyen14** [comment]
@hngu did you figure this issue out? sorry I didn't respond earlier. I'd have some cycles this weekend if you'd like some help figuring it out.

**Comment by hngu** [comment]
@tnguyen14 thats ok we were able to get `.catch` to work and thats good enough for now. My colleague though has spotted another bug :)

https://github.com/tnguyen14/ampersand-sync-with-promise/blob/master/core.js#L135

You should reject with `err || message` so the error callback gets the error message from the server

**Comment by tnguyen14** [comment]
thanks. is this the one filed in #4? If so, I'll try and get to it soon.

**Comment by hngu** [comment]
Yeah correct, sorry didnt realize my colleague already got this in...thank you!
