### ISSUE TITLE
Error messages not surfaced in onRejected handlers

### ISSUE THREAD

**Issue by alanshareaholic** [tnguyen14/ampersand-sync-with-promise#4]
When using catch or the then(func, onRejected) syntax if a json error is passed back it doesn't get passed to the onRejected handler function. It looks to be an issue in core.js where when you detect and error, you parse our the json return and pass it to the amersand error handler, but then don't also reject the promise with it if err is missing.

```
 if (options.error) {
   try {
      body = JSON.parse(body);
   } catch(e){}
       var message = (err? err.message : (body || "HTTP"+resp.statusCode));
       options.error(resp, 'error', message);
    }
   reject(err); <- if error it blank here you don't get back anything even if some error json is passed back
```

**Comment by tnguyen14** [comment]
@alanshareaholic what would you suggested solution be here?

`reject` with the `resp` object? or add `message` to the `err` object?

**Comment by alanshareaholic** [comment]
I would add the `resp` to `err` object so that users aren't tied to anything specific as far as passing back errors.

**Comment by tnguyen14** [comment]
@alanshareaholic I've published the new version on npm. Let me know if it works for you guys.
