### ISSUE TITLE
use bluebird instead of then/promise?

### ISSUE THREAD

**Issue by tnguyen14** [tnguyen14/ampersand-sync-with-promise#6]

**Comment by davidowens** [comment]
It would be better to expose a method with which we can inject a specific library / instance of a library.

**Comment by tnguyen14** [comment]
Yeah, that seems to be the right way as well. Any good pattern of how this is done in other places you know of?

**Comment by dazld** [comment]
Mongoose has something like this - http://mongoosejs.com/docs/promises.html (look for 'plugging in your own promises library'). The general pattern is to expose something on the `exports` that consumers of the library can assign a `Promise` constructor to. 

Does that make sense? @david-owens-akqa and I can whip up a PR, if this would be helpful..?

**Comment by dazld** [comment]
Like, not a method, just a straight up exposed property.

**Comment by dazld** [comment]
A small added complexity is for browserifying - ie, should only require stuff that is actually used - so perhaps a different `require/import` point with the default being as you have it now. ie:

``` js
// custom is a different entry point with a codepath that doesn't specifically require a Promise library
import customSync from `ampersand-sync-with-promise/custom`; 
import Promise from 'bluebird';

customSync.Promise = Promise;

// etc

```

something like this.

**Comment by tnguyen14** [comment]
Yeah I agree with the idea of putting it as a property.

I'm not sure having a custom entry point would be a good idea though. I think it'd be good to do

```
import sync from 'ampersand-sync-with-promise';
import Promise from 'bluebird';

sync.Promise = Promise;
```

If it is not set, it will then just use the default promise.

We could also do some checking, so if there's native Promise support, we won't use any of the promise library by default.

**Comment by dazld** [comment]
fine with no custom, was just a thought.

however, if you do specifically set a Promise, then should use that one regardless of native support. fallback to native if nothing is fine.

**Comment by tnguyen14** [comment]
Just wanna provide an update: I'm implementing this with `any-promise`. However, the tests are failing right now as it seems like phantomjs does not have default promise implementation. I'm looking into fixing it. Once I have a branch up, I will create a PR for you guys to review.

**Comment by dazld** [comment]
yep, phantom is a really old version of webkit. you will have to shim something into the global for tests there to work. thanks for looking into it!

**Comment by jnikles** [comment]
I can highly recommend babel-polyfill for this purpose. We are running a stack based in babelify and also use that polyfill for the phantom tests. Pretty straight forward to integrate

**Comment by tnguyen14** [comment]
Thanks everyone. You can follow and participate in that discussion at kevinbeaty/any-promise#11

**Comment by tnguyen14** [comment]
I've created a PR #7 for this, and CC you guys for review.

**Comment by tnguyen14** [comment]
I've published `v4.0.0` that includes this change. Please give it a try if you can, and let me know if you have any feedback.

**Comment by davidowens** [comment]
Great news. I'll give this a try today and report back

**Comment by davidowens** [comment]
It took me longer that I'd hoped because of the holiday in Berlin, but it works great. I've tried it with bluebird, and the global added by babel-polyfill and both work
